### ISSUE TITLE
Add a "require sidecar proxy injection label on namespace" `Constraint` in the ASM bundle?

### ISSUE THREAD

**Issue by mathieu-benoit** [GoogleCloudPlatform/acm-policy-controller-library#29]
Is it planned to add a "require sidecar injection label on namespace" `Constraint` in the ASM bundle?

Today there is the `1.1.2_asm-sidecar-injection` `Constraint` allowing to avoid anyone by passing the sidecar proxy label, but there is no `Constraint` forcing the namespaces in the Mesh to actually have the label.

Here could be an option to achieve that in the ASM bundle?
```
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: namespace-sidecar-injection-label
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Namespace
    excludedNamespaces:
    - config-management-monitoring
    - config-management-system
    - default
    - gatekeeper-system
    - gke-connect
    - istio-system
    - kube-node-lease
    - kube-public
    - kube-system
    - resource-group-system
  parameters:
    labels:
    - allowedRegex: enabled
      key: istio-injection
    - allowedRegex: (asm-managed|asm-managed-rapid|asm-managed-stable)
      key: "istio.io/rev"
```
_Note: this is not working as-is as we need to find a way to have a `OR` and not a `AND` with the 2 labels illustrated above._
