### ISSUE TITLE
Any plan to support Kustomize for each bundle?

### ISSUE THREAD

**Issue by mathieu-benoit** [GoogleCloudPlatform/acm-policy-controller-library#31]
In addition to the Kpt support to customize the bundle, is there any  plan to support Kustomize for each bundle?

Typically having one `kustomization.yaml` file per bundle. With that end-users can leverage this base and add their own overlays on top of that: patch value in parameters (namespace, etc.), add more `Constraints`, etc.

Also, based on [this documentation as an example](https://cloud.google.com/anthos-config-management/docs/how-to/using-asm-security-policy), we could see that there is 2 recommended methods to deploy these bundles:
- `kpt live apply`
- `kpt live apply --dry-run` --> `git commit` --> Config Sync

Here we will add another possibility which could be: `git commit` --> Config Sync - i.e. without the hydration step since Config Sync natively supports Kustomize.

**Comment by apeabody** [comment]
Hi @mathieu-benoit 

Thanks for reaching out!  I'll certainly make sure that Kustomize is added as a feature request to our backlog.

Kpt is also used to directly download the bundle (package), where you thinking to use Kustomize without Kpt?  If so, where you planning to clone the entire repo, or some other flow?  Thanks!

**Comment by mathieu-benoit** [comment]
Hi @apeabody, sure, let me provide more information around that.

I think there are `kpt` users using the existing setup, which is good. But I also think that there are `kustomize` users and/or scenarios. Different and complementary CUJs.

Here are some scenarios that Kustomize could help with:

1. Users who don't have `kpt` install, they could just use `kubectl apply -k` or `kubectl kustomize` commands

1. From their local environment, they can directly deploy 1 remote bundle like this:

```
kubectl apply -k https://github.com/mathieu-benoit/acm-policy-controller-library/bundles/asm-policy-v0.0.1
```

1. They can reference it from their own `kustomization.yaml` file:

```
cat <<EOF > kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/mathieu-benoit/acm-policy-controller-library/bundles/asm-policy-v0.0.1
EOF
kubectl kustomize .
```

1. They can add their own overlays on top of that:

```
cat <<EOF > kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/mathieu-benoit/acm-policy-controller-library/bundles/asm-policy-v0.0.1
# Add their own custom Constraints:
# - my-own-custom-constraint.yaml
patchesStrategicMerge:
# Remove the AsmIngressgatewayLabel Constraint:
- |-
  apiVersion: constraints.gatekeeper.sh/v1beta1
  kind: AsmIngressgatewayLabel
  metadata:
    name: asm-ingressgateway-label
  $patch: delete
# Change the strictnessLevel and enforcementAction + add an excludedNamespaces of one Constraint:
patchesJson6902:
- target:
    kind: AsmSidecarInjection
    name: asm-sidecar-injection
  patch: |-
    - op: replace
      path: /spec/enforcementAction
      value: deny
    - op: replace
      path: /spec/parameters/strictnessLevel
      value: Low
    - op: add
      path: /spec/match/excludedNamespaces/-
      value: test
EOF
kubectl kustomize .
```

I can work on the implementation and documentation of this in this repo, see my fork already starting here: https://github.com/mathieu-benoit/acm-policy-controller-library.

Also, it would be great to have a dedicated tab with this Kustomize way in our Policies bundles [here](https://cloud.google.com/anthos-config-management/docs/how-to/using-constraints-to-enforce-pod-security), [here](https://cloud.google.com/anthos-config-management/docs/how-to/using-cis-k8s-benchmark), [here](https://cloud.google.com/anthos-config-management/docs/how-to/using-asm-security-policy) and [here](https://cloud.google.com/anthos-config-management/docs/how-to/using-policy-essentials-v2022). I can help on this too.

Let me know if that makes sense, if you have any questions/concerns, happy to elaborate and collaborate more on this.

**Comment by mathieu-benoit** [comment]
Also, just would like to add that is what the Gatekeeper library provided too: https://github.com/open-policy-agent/gatekeeper-library/tree/master/library

**Comment by apeabody** [comment]
Thanks @mathieu-benoit! - Let me connect with your directly on details.

**Comment by mathieu-benoit** [comment]
Hey @apeabody, I finally got the chance to do two tests with Config Sync, and there is no issues.

Test 1 with the current repo without Kustomization file:
```
cat <<EOF > acm-config.yaml
applySpecVersion: 1
spec:
  configSync:
    enabled: true
    sourceFormat: unstructured
    syncRepo: https://github.com/GoogleCloudPlatform/acm-policy-controller-library
    syncBranch: main
    secretType: none
    policyDir: bundles/policy-essentials-v2022
  policyController:
    enabled: true
    templateLibraryInstalled: true
    referentialRulesEnabled: true
EOF
```
Results:
```
nomos status --contexts $(k config current-context)
Connecting to clusters...

*gke_mabenoit-tuto-1_us-east4-a_cs-gke-1-25
  --------------------
  <root>:root-sync   https://github.com/GoogleCloudPlatform/acm-policy-controller-library/bundles/policy-essentials-v2022@main   
  SYNCED             5b9a4251c8fb764a73ebe96f9a37a8a41471613c                                                                    
  Managed resources:
     NAMESPACE   NAME                                                                                                                       STATUS    SOURCEHASH
                 k8snoenvvarsecrets.constraints.gatekeeper.sh/policy-essentials-v2022-no-secrets-as-env-vars                                Current   5b9a425
                 k8spodsrequiresecuritycontext.constraints.gatekeeper.sh/policy-essentials-v2022-pods-require-security-context              Current   5b9a425
                 k8sprohibitrolewildcardaccess.constraints.gatekeeper.sh/policy-essentials-v2022-prohibit-role-wildcard-access              Current   5b9a425
                 k8spspallowedusers.constraints.gatekeeper.sh/policy-essentials-v2022-psp-pods-must-run-as-nonroot                          Current   5b9a425
                 k8spspallowprivilegeescalationcontainer.constraints.gatekeeper.sh/policy-essentials-v2022-psp-allow-privilege-escalation   Current   5b9a425
                 k8spspcapabilities.constraints.gatekeeper.sh/policy-essentials-v2022-psp-capabilities                                      Current   5b9a425
                 k8spsphostnamespace.constraints.gatekeeper.sh/policy-essentials-v2022-psp-host-namespace                                   Current   5b9a425
                 k8spsphostnetworkingports.constraints.gatekeeper.sh/policy-essentials-v2022-psp-host-network-ports                         Current   5b9a425
                 k8spspprivilegedcontainer.constraints.gatekeeper.sh/policy-essentials-v2022-psp-privileged-container                       Current   5b9a425
                 k8spspseccomp.constraints.gatekeeper.sh/policy-essentials-v2022-psp-seccomp-default                                        Current   5b9a425
                 k8srestrictrolebindings.constraints.gatekeeper.sh/policy-essentials-v2022-restrict-clusteradmin-rolebindings               Current   5b9a425
```

Test 2 with my fork containing a Kustomization file at the root of each bundle:
```
cat <<EOF > acm-config.yaml
applySpecVersion: 1
spec:
  configSync:
    enabled: true
    sourceFormat: unstructured
    syncRepo: https://github.com/mathieu-benoit/acm-policy-controller-library
    syncBranch: main
    secretType: none
    policyDir: bundles/policy-essentials-v2022
  policyController:
    enabled: true
    templateLibraryInstalled: true
    referentialRulesEnabled: true
EOF
```
Results:
```
nomos status --contexts $(k config current-context)
Connecting to clusters...

*gke_mabenoit-tuto-1_us-east4-a_cs-gke-1-25
  --------------------
  <root>:root-sync   https://github.com/mathieu-benoit/acm-policy-controller-library/bundles/policy-essentials-v2022@main   
  SYNCED             a4b0f3a84a9cb7295ae4fec0c340e0f93b236545                                                               
  Managed resources:
     NAMESPACE   NAME                                                                                                                       STATUS    SOURCEHASH
                 k8snoenvvarsecrets.constraints.gatekeeper.sh/policy-essentials-v2022-no-secrets-as-env-vars                                Current   a4b0f3a
                 k8spodsrequiresecuritycontext.constraints.gatekeeper.sh/policy-essentials-v2022-pods-require-security-context              Current   a4b0f3a
                 k8sprohibitrolewildcardaccess.constraints.gatekeeper.sh/policy-essentials-v2022-prohibit-role-wildcard-access              Current   a4b0f3a
                 k8spspallowedusers.constraints.gatekeeper.sh/policy-essentials-v2022-psp-pods-must-run-as-nonroot                          Current   a4b0f3a
                 k8spspallowprivilegeescalationcontainer.constraints.gatekeeper.sh/policy-essentials-v2022-psp-allow-privilege-escalation   Current   a4b0f3a
                 k8spspcapabilities.constraints.gatekeeper.sh/policy-essentials-v2022-psp-capabilities                                      Current   a4b0f3a
                 k8spsphostnamespace.constraints.gatekeeper.sh/policy-essentials-v2022-psp-host-namespace                                   Current   a4b0f3a
                 k8spsphostnetworkingports.constraints.gatekeeper.sh/policy-essentials-v2022-psp-host-network-ports                         Current   a4b0f3a
                 k8spspprivilegedcontainer.constraints.gatekeeper.sh/policy-essentials-v2022-psp-privileged-container                       Current   a4b0f3a
                 k8spspseccomp.constraints.gatekeeper.sh/policy-essentials-v2022-psp-seccomp-default                                        Current   a4b0f3a
                 k8srestrictrolebindings.constraints.gatekeeper.sh/policy-essentials-v2022-restrict-clusteradmin-rolebindings               Current   a4b0f3a
```
