### ISSUE TITLE
`restrict-clusteradmin-rolebindings` `Constraints` in CIS and Essentials are blocking the deployment of Config Sync's default `RootSync`

### ISSUE THREAD

**Issue by mathieu-benoit** [GoogleCloudPlatform/acm-policy-controller-library#38]
If I deploy PoCo with the default library enabled:
```
cat <<EOF > acm-config.yaml
applySpecVersion: 1
spec:
  configSync:
    enabled: true
  policyController:
    enabled: true
    templateLibraryInstalled: true
    referentialRulesEnabled: true
EOF
gcloud beta container fleet config-management apply     --membership ${CLUSTER_NAME}     --config acm-config.yaml
```
Then, deploy all the bundles in this repo.

And then try to deploy my first default `RootSync`:
```
cat <<EOF > acm-config.yaml
applySpecVersion: 1
spec:
  configSync:
    enabled: true
    sourceFormat: unstructured
    syncRepo: https://github.com/mathieu-benoit/acm-policy-controller-library
    syncBranch: main
    secretType: none
    policyDir: bundles/policy-essentials-v2022
  policyController:
    enabled: true
    templateLibraryInstalled: true
    referentialRulesEnabled: true
EOF
gcloud beta container fleet config-management apply     --membership ${CLUSTER_NAME}     --config acm-config.yaml
```
My CS deployment will be stucked/blocked and if I look at the my events `k get events -A` or my `Constraints` `k get constraints`, I can see those errors:
```
$ kubectl get k8srestrictrolebindings.constraints.gatekeeper.sh/cis-k8s-v1.5.1-restrict-clusteradmin-rolebindings -ojsonpath='{.status.violations}'  | jq
[
  {
    "enforcementAction": "dryrun",
    "group": "rbac.authorization.k8s.io",
    "kind": "ClusterRoleBinding",
    "message": "ClusterRoleBinding is restricted from referencing ClusterRole cluster-admin",
    "name": "configsync.gke.io:root-reconciler",
    "version": "v1"
  },
  {
    "enforcementAction": "dryrun",
    "group": "rbac.authorization.k8s.io",
    "kind": "ClusterRoleBinding",
    "message": "ClusterRoleBinding is restricted from referencing ClusterRole cluster-admin",
    "name": "storage-version-migration-migrator-v2",
    "version": "v1"
  }
]
```
And:
```
$ kubectl get k8srestrictrolebindings.constraints.gatekeeper.sh/policy-essentials-v2022-restrict-clusteradmin-rolebindings -ojsonpath='{.status.violations}'  | jq 
[
  {
    "enforcementAction": "dryrun",
    "group": "rbac.authorization.k8s.io",
    "kind": "ClusterRoleBinding",
    "message": "ClusterRoleBinding is restricted from referencing ClusterRole cluster-admin",
    "name": "configsync.gke.io:root-reconciler",
    "version": "v1"
  },
  {
    "enforcementAction": "dryrun",
    "group": "rbac.authorization.k8s.io",
    "kind": "ClusterRoleBinding",
    "message": "ClusterRoleBinding is restricted from referencing ClusterRole cluster-admin",
    "name": "storage-version-migration-migrator-v2",
    "version": "v1"
  }
]

```
For `storage-version-migration-migrator-v2`, I don't think it's related to Config Sync, but that needs to be fixed too. I created my GKE cluster in `rapid` channel with version `v1.25.0-gke.1100`, JFYI.

_Note: I haven't tried yet with a secondary `RootSync` (not named `root-sync`), I will do the test and will report back here then._

**Comment by apeabody** [comment]
Hi @mathieu-benoit - Thanks for reaching out!

Would you be able to provide a `kubectl describe ClusterRoleBinding` for the above `configsync.gke.io:root-reconciler` and `storage-version-migration-migrator-v2`?

**Comment by mathieu-benoit** [comment]
Sure, here you are:
```
kubectl get ClusterRoleBinding configsync.gke.io:root-reconciler -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2022-10-05T14:04:37Z"
  name: configsync.gke.io:root-reconciler
  resourceVersion: "2399248"
  uid: b5903767-05df-4f78-88cd-03487325d59d
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: root-reconciler
  namespace: config-management-system
```
And:
```
kubectl get ClusterRoleBinding  storage-version-migration-migrator-v2 -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    components.gke.io/component-name: storageversionmigrator-rbac
    components.gke.io/component-version: 0.0.4
  creationTimestamp: "2022-10-02T17:00:08Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  name: storage-version-migration-migrator-v2
  resourceVersion: "691"
  uid: 8aa4bcad-4676-4060-bff6-4133f9187562
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:storageversionmigrator
```

**Comment by apeabody** [comment]
Thanks @mathieu-benoit! - Can you please confirm you are using the most recent version of the CIS and Policy Essentials bundles?

For example, this CIS constraint: https://github.com/GoogleCloudPlatform/acm-policy-controller-library/blob/main/bundles/cis-k8s-v1.5.1/5.1.1_restrict-clusteradmin-rolebindings.yaml

**Comment by mathieu-benoit** [comment]
I'm, I just re-tested with:
```
cat <<EOF > acm-config.yaml
applySpecVersion: 1
spec:
  configSync:
    enabled: true
    sourceFormat: unstructured
    syncRepo: https://github.com/GoogleCloudPlatform/acm-policy-controller-library
    syncBranch: main
    secretType: none
    policyDir: bundles/policy-essentials-v2022 policy
  policyController:
    enabled: true
    templateLibraryInstalled: true
    referentialRulesEnabled: true
EOF
```
